nama          = input("Nama                   : ")
NIM           = input("NIM                    : ")
kelas_paralel = input("Kelas Paralel          : ")
Ttl           = input("Tempat/Tanggal Lahir   : ")
alamat        = input("Alamat                 : ")
hobi          = input("Hobby                  : ")
No            = input("No. HP                 : ")
print("")

print("Nama                   : " + nama)
print("NIM                    : " + NIM)
print("Kelas Paralel          : " + kelas_paralel)
print("Tempat/Tanggal Lahir   : " + Ttl)
print("Alamat                 : " + alamat)
print("Hobby                  : " + hobi)
print("No. HP                 : " + No)